/**
 * Console Component
 * 
 * Handles message display, scrolling, and filtering.
 */

import type { ParsedMessage, DebugLevel, Filter } from '../types';

export class Console {
  private container: HTMLElement;
  private messages: ParsedMessage[] = [];
  private filteredMessages: ParsedMessage[] = [];
  private filterText = '';
  private filters: Filter[] = [];
  private useFilterChips = false;
  private autoScroll = true;
  private fontSize = 13;
  private messageIdCounter = 0;
  private pendingMessages: ParsedMessage[] = [];
  private renderScheduled = false;

  constructor(container: HTMLElement) {
    this.container = container;
    this.showWelcome();
    this.setupScrollListener();
  }

  /**
   * Show welcome message in empty console
   */
  private showWelcome(): void {
    this.container.innerHTML = `
      <div class="console__welcome">
        <p>Welcome to WSTerm</p>
        <p class="console__welcome-hint">Enter device IP address and click Connect</p>
      </div>
    `;
  }

  /**
   * Setup scroll listener for auto-scroll detection
   */
  private setupScrollListener(): void {
    // The container itself has overflow-y: auto
    this.container.addEventListener('scroll', () => {
      if (!this.autoScroll) return;
      
      const isAtBottom = this.container.scrollHeight - this.container.scrollTop 
        <= this.container.clientHeight + 50;
      
      // Show "new messages" button when scrolled up
      const scrollBtn = document.getElementById('scrollToBottomBtn');
      if (scrollBtn) {
        scrollBtn.hidden = isAtBottom;
      }
    });

    // Scroll to bottom button
    const scrollBtn = document.getElementById('scrollToBottomBtn');
    scrollBtn?.addEventListener('click', () => {
      this.scrollToBottom();
      scrollBtn.hidden = true;
    });
  }

  /**
   * Append a parsed message to the console
   * Uses batched rendering to prevent browser freeze
   */
  appendMessage(message: ParsedMessage): void {
    this.messages.push(message);
    
    // Apply filter
    if (this.matchesFilter(message)) {
      this.filteredMessages.push(message);
      this.pendingMessages.push(message);
      this.scheduleRender();
    }

    // Limit buffer size
    if (this.messages.length > 10000) {
      this.messages.shift();
      this.filteredMessages = this.messages.filter(m => this.matchesFilter(m));
      this.rerender();
    }
  }

  /**
   * Schedule a batched render using requestAnimationFrame
   */
  private scheduleRender(): void {
    if (this.renderScheduled) return;
    
    this.renderScheduled = true;
    requestAnimationFrame(() => {
      this.flushPendingMessages();
      this.renderScheduled = false;
    });
  }

  /**
   * Render all pending messages in a batch
   */
  private flushPendingMessages(): void {
    if (this.pendingMessages.length === 0) return;

    // Remove welcome message if present
    const welcome = this.container.querySelector('.console__welcome');
    if (welcome) {
      welcome.remove();
    }

    // Create document fragment for batch DOM insertion
    const fragment = document.createDocumentFragment();
    
    for (const message of this.pendingMessages) {
      const row = this.createMessageRow(message);
      fragment.appendChild(row);
    }

    this.container.appendChild(fragment);
    this.pendingMessages = [];

    if (this.autoScroll) {
      this.scrollToBottom();
    }
  }

  /**
   * Append a system message (generated by app, not device)
   */
  appendSystemMessage(text: string, _level: 'info' | 'error' = 'info'): void {
    const message: ParsedMessage = {
      id: `msg-${++this.messageIdCounter}`,
      type: 'system',
      content: text,
      raw: text,
      receivedAt: Date.now(),
    };
    
    this.appendMessage(message);
  }

  /**
   * Create a message row element (without appending to DOM)
   */
  private createMessageRow(message: ParsedMessage): HTMLElement {
    const row = document.createElement('div');
    row.className = `console__message console__message--${message.type}`;
    row.dataset.id = message.id;
    
    if (message.level) {
      row.classList.add(`console__message--level-${message.level}`);
    }

    // Build message content
    const parts: string[] = [];

    // Timestamp (if available)
    if (message.timestamp !== undefined) {
      parts.push(`<span class="msg-time">${this.formatTimestamp(message.timestamp)}</span>`);
    }

    // Level badge
    if (message.level) {
      const levelLetter = this.getLevelLetter(message.level);
      parts.push(`<span class="msg-level msg-level--${message.level}">[${levelLetter}]</span>`);
    }

    // Function and core (if available)
    if (message.function) {
      parts.push(`<span class="msg-func">(${message.function})</span>`);
    }
    if (message.core !== undefined) {
      parts.push(`<span class="msg-core">(C${message.core})</span>`);
    }

    // Message content
    parts.push(`<span class="msg-content">${this.escapeHtml(message.content)}</span>`);

    row.innerHTML = parts.join(' ');
    return row;
  }

  /**
   * Render a single message to the DOM (for individual adds)
   */
  private renderMessage(message: ParsedMessage): void {
    // Remove welcome message if present
    const welcome = this.container.querySelector('.console__welcome');
    if (welcome) {
      welcome.remove();
    }

    const row = this.createMessageRow(message);
    this.container.appendChild(row);
  }

  /**
   * Clear all messages
   */
  clear(): void {
    this.messages = [];
    this.filteredMessages = [];
    this.container.innerHTML = '';
  }

  /**
   * Set filter text
   */
  setFilter(text: string): void {
    this.filterText = text.toLowerCase();
    this.filteredMessages = this.messages.filter(m => this.matchesFilter(m));
    this.rerender();
  }

  /**
   * Enable/disable chip-based filters (prototype)
   */
  enableFilterChips(enabled: boolean): void {
    this.useFilterChips = enabled;
    if (!enabled) {
      this.filters = [];
    }
    this.filteredMessages = this.messages.filter(m => this.matchesFilter(m));
    this.rerender();
  }

  /**
   * Set filter chips (AND across enabled chips)
   */
  setFilters(filters: Filter[]): void {
    this.filters = filters;
    this.filteredMessages = this.messages.filter(m => this.matchesFilter(m));
    this.rerender();
  }

  /**
   * Check if message matches current filter
   */
  private matchesFilter(message: ParsedMessage): boolean {
    const content = message.content.toLowerCase();
    const raw = message.raw.toLowerCase();

    if (this.useFilterChips) {
      for (const filter of this.filters) {
        if (!filter.enabled) continue;
        const needle = filter.raw.toLowerCase();
        if (!content.includes(needle) && !raw.includes(needle)) {
          return false;
        }
      }
      return true;
    }

    if (!this.filterText) return true;
    return content.includes(this.filterText) || raw.includes(this.filterText);
  }

  /**
   * Re-render all filtered messages
   */
  private rerender(): void {
    this.container.innerHTML = '';
    
    for (const message of this.filteredMessages) {
      this.renderMessage(message);
    }

    if (this.autoScroll) {
      this.scrollToBottom();
    }
  }

  /**
   * Set auto-scroll enabled state
   */
  setAutoScroll(enabled: boolean): void {
    this.autoScroll = enabled;
    if (enabled) {
      this.scrollToBottom();
    }
  }

  /**
   * Set font size
   */
  setFontSize(size: number): void {
    this.fontSize = size;
    this.container.style.fontSize = `${size}px`;
  }

  /**
   * Scroll to bottom of console
   */
  scrollToBottom(): void {
    // The container itself has overflow-y: auto, so scroll it directly
    this.container.scrollTop = this.container.scrollHeight;
  }

  /**
   * Get plain text content for clipboard
   */
  getTextContent(): string {
    return this.filteredMessages
      .map(m => m.raw)
      .join('\n');
  }

  /**
   * Format timestamp from milliseconds
   */
  private formatTimestamp(ms: number): string {
    const seconds = Math.floor(ms / 1000);
    const minutes = Math.floor(seconds / 60);
    const hours = Math.floor(minutes / 60);
    
    const hh = String(hours % 24).padStart(2, '0');
    const mm = String(minutes % 60).padStart(2, '0');
    const ss = String(seconds % 60).padStart(2, '0');
    const mmm = String(ms % 1000).padStart(3, '0');
    
    return `${hh}:${mm}:${ss}.${mmm}`;
  }

  /**
   * Get single letter for debug level
   */
  private getLevelLetter(level: DebugLevel): string {
    const letters: Record<DebugLevel, string> = {
      1: 'V', 2: 'D', 3: 'I', 4: 'W', 5: 'E'
    };
    return letters[level] || '?';
  }

  /**
   * Escape HTML to prevent XSS
   */
  private escapeHtml(text: string): string {
    const div = document.createElement('div');
    div.textContent = text;
    return div.innerHTML;
  }
}
